### ISSUE TITLE
Media queries aren't executed in IE 8, even though we're using respond.js

### ISSUE THREAD

**Issue by jonlow** [thememphisagency/fcbresponsive#1]
The site breaks in IE 8 (IE 8 Standard Mode) because the media queries aren't being executed. We're using the respond.js https://github.com/scottjehl/Respond pollyfill to support media queries in IE 8 but it doesn't seem like it's working.

I've tested the respond.js demo (see github link) and it works in IE 8, so there's something wrong with our code

**Comment by yorky001** [comment]
Checked and this is now fixed by Matty adding a Custom modernizr script that included the Media query check.
