### ISSUE TITLE
Need a contact form design and developed and integrated into FarCry

### ISSUE THREAD

**Issue by smebberson** [thememphisagency/fcbresponsive#10]
Needs to be integrated into fcbPostOffice

**Comment by yorky001** [comment]
In mobile view.... do we need a bit of space between the buttons?

**Comment by jonlow** [comment]
Get rid of the fcbshop reference that is causing this error: 

http://screencast.com/t/poxRn7RC

Also, not sure why my test failed in the first place?

Also get a designer to review the work on this. Yes the mobile buttons are too close
