### ISSUE TITLE
Footer navigation needs to be rewired in

### ISSUE THREAD

**Issue by smebberson** [thememphisagency/fcbresponsive#17]

**Comment by yorky001** [comment]
Reopened to include handpicked rule footer links

**Comment by yorky001** [comment]
Added 2 new rules: Rule Footer Links and Rule Contact Us.

**Comment by jonlow** [comment]
The contact us display in the footer should just use the Rule Footer Links (e.g we don't need the rule contact us).

Use the Rule footer links to handpick an fcbContact record, and then choose a display method to display the contact info as is.

Basically, I want the contact info against a fcbContact record in farcry and just convert the existing display styles into a display method for fcbContact. We can then re-use the footer links rule and remove the contact rule which keeps it simple for the client
