### ISSUE TITLE
Use new Galleria Banner Version + Style review

### ISSUE THREAD

**Issue by jonlow** [thememphisagency/fcbresponsive#25]
Use new Galleria version (currently using 1.2.9 beta) and do a style review with a designer of the banner.

Also, move galleria folder in js to the js/libs folder and update the references to galleria accordingly

**Comment by yorky001** [comment]
Design review complete. Changed bgColour of nav bar and dot off colour

**Comment by yorky001** [comment]
Not working in some browsers - reopening

**Comment by yorky001** [comment]
Now working in FF and IE 8/9
