### ISSUE TITLE
Youtube Integration

### ISSUE THREAD

**Issue by jonlow** [thememphisagency/fcbresponsive#30]
Make sure that our youtube integration works so that you can: 
- add a youtube video via the wysiwyg
- add a youtube video via a rule
### Responsive

Use FitVids (http://fitvidsjs.com/) to make sure the video has the correct aspect ratio when responsive. I'm happy to make the call that all youtube videos should be full width of the container they're in, so in the wysiwyg don't let the user set the size of the youtube video as this will mess it up for mobile and tablets etc.

**Comment by matthewattanasio** [comment]
Need the latest of fcblib for this to work correclty on local
