### ISSUE TITLE
Need to build a responsive drop down navigation

### ISSUE THREAD

**Issue by smebberson** [thememphisagency/fcbresponsive#5]
We need a design for second level drop down navigation will work on mobile as well as desktop

**Comment by jonlow** [comment]
Still jumpy so re-opening

**Comment by jonlow** [comment]
To fix this, I would simply create a new local test branch, checkout that branch and revert it back to the mobile nav that wasn't jumpy (e.g without the multiple desktop dropdowns) and see how the js and css is applied as it was really  smooth in that version. Then just get what you need and put it into master

**Comment by yorky001** [comment]
I had commented out the wrong "e.preventdefault()" so it was jumping to #menu hashtag.
