### ISSUE TITLE
Search results need to be integrated into FarCry

### ISSUE THREAD

**Issue by smebberson** [thememphisagency/fcbresponsive#6]

**Comment by matthewattanasio** [comment]
This is now completed according to Flavios design suggestions

**Comment by matthewattanasio** [comment]
Need to have pagination styles added and review by designer

**Comment by jonlow** [comment]
No worries, I've added the Design Required label. Mark this as feedback when complete and ready to be reviewed

**Comment by jonlow** [comment]
Matt still working on core functionality changes

**Comment by jonlow** [comment]
Get Phil or flav to review the work on this. Things like position of the result text and the button rounded search button look off
